#VECTORS
# Exercise 1
u<-4
v<-8
u+v
v-u
u*v
u/v
v^u
#Exercise 2
u<-c(4,5,6)
v<-c(1,2,3)
u+v
u-v
u*v
u/v
v^u
#Exercise 3
u<-c(8,9,10)
v<-c(1,2,3)
w<-(2*u+v)/10
w<-2*u
w<-w+v
w<-w/10
w<-(u+0.5*v)^2
w
w<-0.5*2
w<-u+w
w<-w^2
w
w<-(u+2)*(u-5)+v
w
w<-u+2
w<-w*(u-5)
w<-w+v
w
w<-(u+2)/((u-5)*v)
w
w<-u-5
w<-w*v
w<-(u+2)/w
w
#Exercise 4
#Part a
w<-u+v
w<-w/2
w<-w+4
w
w<-((u+v)/2)+u
w
#Part b
w1<-u^3
w2<-u-3
w<-w1/w2
w
w<-(u^3)/(u-v)
w
#Data Frames
Name<-c("Alex","Lilly","Mark","Oliver")
Weight<-c(57,69,83,75)
Height<-c(177,163,190,179)
Age<-c(25,31,23,52)
Sex<-as.factor(c("F","F","M","F"))
df<-data.frame(row.names=Name,Age,Height,Weight,Sex)
levels(df$Sex)
levels(df$Sex)<-c("M","F")
df
Working<-c("Yes","No","No","Yes")
Name<-c("Alex","Lilly","Mark","Oliver")
df2<-data.frame(row.names=Name,Working)
df2
df<-cbind(df,df2)
dim(df)
class(state.center)
data.state<-as.data.frame(state.center)
a<-(rnorm(10))
b<-letters(4:13)
c<-c("Yes","No","No","No","No","Yes","No","Yes","Yes","No")
df3<-data.frame(a,b,c)
df3[with(df3,order(a)),]
matrix.data<-matrix(1:10,nrow=5,ncol=2)
df<-as.data.frame(matrix.data)
colnames(df)<-paste("variable-",1:ncol(df))
rownames(df)<-paste("id-",1:nrow(df))
df
class(VADeaths)
df<-data.frame(VADeaths)
df$Total<-rowSums(df)
df<-df[,c(5,1,2,3,4)]
df
class(state.x77)
df2<-data.frame(state.x77)
nrow(df2[df2$Income<4300])
row.names(df2[which.max(df2$Income,)])